export enum NotificationType {
    WON_BET = 'WON_BET',
    LOST_BET = 'LOST_BET',
    CANCEL_BET = 'CANCEL_BET',
    WON_MULTIPLE_BET = 'WON_MULTIPLE_BET',
    LOST_MULTIPLE_BET = 'LOST_MULTIPLE_BET',
    CANCEL_MULTIPLE_BET = 'CANCEL_MULTIPLE_BET',
    UPDATE_MULTIPLE_BET = 'UPDATE_MULTIPLE_BET', 
    ODDS_CHANGED = 'ODDS_CHANGED',
    FINISHED_GAME = 'FINISHED_GAME',
    CANCEL_GAME = 'CANCEL_GAME',
}